export const ESTATUS_DOC_OPTIONS = [
    { value: 'ampliacion_turno', label: 'Ampliación de turno' },
    { value: 'aprobado', label: 'Aprobado' },
    { value: 'aprobado_camara_diputados', label: 'Aprobado, pasó a la Cámara de Diputados' },
    { value: 'aprobado_camara_diputados_modificaciones', label: 'Aprobado, pasó a la Cámara de Diputados con modificaciones' },
    { value: 'aprobado_ejecutivo_federal', label: 'Aprobado, pasó al Ejecutivo Federal' },
    { value: 'aprobado_senado', label: 'Aprobado, pasó al Senado de la República' },
    { value: 'aprobado_senado_modificaciones', label: 'Aprobado, pasó al Senado de la República con modificaciones' },
    { value: 'comuniquese', label: 'Comuníquese' },
    { value: 'urgente_aprobado', label: 'De urgente resolución – Aprobado' },
    { value: 'devuelto_comision_dictaminadora', label: 'Devuelto a la comisión dictaminadora' },
    { value: 'devuelto_comisiones_dictaminadoras', label: 'Devuelto a la comisiones dictaminadoras' },
    { value: 'dictamen_negativo_desechado_pleno', label: 'Dictamen sentido negativo - desechado en el pleno' },
    { value: 'declaratoria_publicidad_dictamen', label: 'Declaratoria de Publicidad de Dictamen' },
    { value: 'dictamen_primera_lectura', label: 'Dictamen de primera lectura ante el pleno' },
    { value: 'dictamen_segunda_lectura', label: 'Dictamen de segunda lectura y discusión en el pleno' },
    { value: 'dictamen_desechado_pleno', label: 'Dictamen desechado en el pleno' },
    { value: 'dictamen_negativo', label: 'Dictamen en sentido negativo' },
    { value: 'iniciativa_no_competencia_colegisladora', label: 'Iniciativa de no competencia, turnada a la Colegisladora' },
    { value: 'iniciativa_comisiones_unidas', label: 'Iniciativa turnada a Comisiones Unidas para dictamen' },
    { value: 'iniciativa_comision_dictamen', label: 'Iniciativa turnada a Comisión para dictamen' },
    { value: 'iniciativa_comision_opinion', label: 'Iniciativa turnada a Comisión para opinión' },
    { value: 'minuta_aprobada_ejecutivo_federal', label: 'Minuta aprobada, pasó al Ejecutivo federal' },
    { value: 'minuta_comision_dictamen', label: 'Minuta turnada a Comisión para dictamen' },
    { value: 'minuta_comision_opinion', label: 'Minuta turnada a Comisión para opinión' },
    { value: 'minuta_comisiones_unidas', label: 'Minuta turnada a Comisiones Unidas para dictamen' },
    { value: 'mocion_suspensiva', label: 'Moción suspensiva' },
    { value: 'publicada_gaceta', label: 'Publicada en la Gaceta Parlamentaria' },
    { value: 'punto_acuerdo_comision_dictamen', label: 'Punto de acuerdo turnado a Comisión para dictamen' },
    { value: 'punto_acuerdo_comisiones_unidas', label: 'Punto de acuerdo turnado a Comisiones Unidas para dictamen' },
    { value: 'punto_acuerdo_junta_coordinacion', label: 'Punto de acuerdo turnado a Junta de Coordinación Política' },
    { value: 'se_turnara_comision', label: 'Se turnará a la comisión correspondiente' },
    { value: 'no_presentado_pleno', label: 'No se presentó al pleno' },
    { value: 'oficio_comision', label: 'Oficio turnado a Comisión' },
    { value: 'oficio_comisiones_unidas', label: 'Oficio Turnado a Comisiones Unidas' },
    { value: 'remitida_camara_diputados', label: 'Remitida a Cámara de Diputados' },
    { value: 'pospone_discusion', label: 'Se pospone su discusión' },
    { value: 'enterado', label: 'Enterado' },
    { value: 'remitida_senado', label: 'Remitida al Senado de la República' },
    { value: 'excitativa_comisiones', label: 'Excitativa remitida a Comisiones' },
    { value: 'excitativa_comision', label: 'Excitativa remitida a Comisión' },
    { value: 'presenta', label: 'Presenta' },
    { value: 'acuerdo_parlamentario', label: 'Acuerdo Parlamentario' },
    { value: 'aprobado_congresos_locales', label: 'Aprobado, turnado a Congresos Locales' },
    { value: 'aprobado_comuniquese', label: 'Aprobado, Comuníquese' },
    { value: 'dictamen_pleno', label: 'Dictamen ante el pleno' },
    { value: 'aprobado_ejecutivo_estado', label: 'Aprobado, pasó al Poder Ejecutivo del Estado' },
    { value: 'publicado_diario_oficial', label: 'Publicado en el Diario Oficial de la Federación' },
    { value: 'publicado_periodico_oficial', label: 'Publicado en el Periódico Oficial' },
    { value: 'dictamen_positivo', label: 'Dictamen en sentido positivo' },
    { value: 'dictamen_discusion_pleno', label: 'Dictamen a discusión en el pleno' },
    { value: 'desahogado', label: 'Desahogado' },
    { value: 'dictamen_aprobado_comision', label: 'Dictamen aprobado en comisión' },
    { value: 'dictamen_aprobado_comisiones_unidas', label: 'Dictamen aprobado en comisiones unidas' },
    { value: 'dictamen_desechado_comision', label: 'Dictamen desechado en comisión' },
    { value: 'dictamen_desechado_comisiones_unidas', label: 'Dictamen desechado en comisiones unidas' },
    { value: 'solicitud_prorroga', label: 'Solicitud de Prórroga' }
];
